export PATH="/usr/local/sbin:$PATH"
export PATH="${DIR_FOR_BINARIES}:$PATH"
export PATH="${DIR_FOR_BINARY_REFS}:$PATH"
export PATH="${DIR_FOR_BINARIES}/cdap-sdk-4.0.1/bin:$PATH"
export PATH="${DIR_FOR_BINARIES}/git-2.12.0/bin:$PATH"