# CHECKVIST key
  export CHECKVIST_KEY='ykZu5MT9QoaMYJ'
# IFTTT key
  export IFTTT_KEY="dPCy-54eECsRA-uBwwO20B"

# Macys Mongo URI
  # mongo_uri=mongodb://c12e:C0gScal3@aws-us-east-1-portal.12.dblayer.com:10476,aws-us-east-1-portal.13.dblayer.com:11005/macys_rancher_test?ssl=true
# URL that Rancher is on
  export RANCHER_URL=http://rancher-dev.insights.ai:8080/
# Set the access key, i.e. username
  export RANCHER_ACCESS_KEY=3F58CCBDD8D35E9332BE
# Set the secret key, i.e. password
  export RANCHER_SECRET_KEY=SdKSFbqzmV2XkhPANKhdTfEG9nCa1JbX1tHJDi1r

# NPM Token to Connect to Artifactory
  export NPM_TOKEN="eyJ2ZXIiOiIyIiwidHlwIjoiSldUIiwiYWxnIjoiUlMyNTYiLCJraWQiOiJzZDFZZGNPTmJGVVdCVDBQYVU2OFQzZ25pbWo2emxLUExaME5XZDhtSV9vIn0.eyJzdWIiOiJqZi1hcnRpZmFjdG9yeUBlYzVlOWIwYy0wMjRlLTQ2YjktOTIzYy02MTc5ZjFjYjY3OWZcL3VzZXJzXC9jMTJlLWRldiIsInNjcCI6Im1lbWJlci1vZi1ncm91cHM6KiBhcGk6KiIsImF1ZCI6ImpmLWFydGlmYWN0b3J5QGVjNWU5YjBjLTAyNGUtNDZiOS05MjNjLTYxNzlmMWNiNjc5ZiIsImlzcyI6ImpmLWFydGlmYWN0b3J5QGVjNWU5YjBjLTAyNGUtNDZiOS05MjNjLTYxNzlmMWNiNjc5ZiIsImlhdCI6MTUxMTIwNDQ4MCwianRpIjoiMWMwMTgyM2QtMWMyNC00MmRhLWE0ZjgtOTBiYTRkYmZiNTQyIn0.FuLgish1oteeBfR1ek8u86EDbGAsjs_QOXDxGFRo6Z8yCMlaKU8VIAqC7Z9J5V8nZk3ziDxeDTQG5khuFSYcAGroFppjGetacTB67FNyoLwMgB5cYdsqP9aswJPfKhqV6HFjrd0coW8itgmN2sP8ZvyGrBZsDGLawC8lFlV1ZkQ8-1Q_eGQVd4IfdAQ2YyuFfAPdeJ-itgcbyuWqw_cdefBDHXjdXzb0ZbNWNibVxIoCLNAkoxCVLFIdV4z7AehR-OYLKygHyh8dXnsg6VdjSEvFaut3X2IUYMV3MkjYMLhD4USlUlxL-9jPcnztEvzpFKrxsVpzwGSUtz7okdhNLw"
