#!/bin/bash

function html_encode_path() {
  # python -c 'import urllib.parse, sys; print(urllib.parse.quote(sys.stdin.read().strip()))'
  python -c 'import urllib.parse, sys; l = sys.stdin.read().strip().split("\n"); [ print(urllib.parse.quote(x.strip())) for x in l]'
}

html_encode_path
