#!/bin/bash
PADDING=120
FILE="${1}"
PADDED_FILE=$(echo "${1}" | sed "s#${PWD}#.#")
PADDED_FILE=$(printf "%${PADDING}s" "${PADDED_FILE}")
LINE="${2:-1}"
# echo -e "\t${FILE}" >&2
# echo -e "\t${LINE}" >&2
print-link "${PADDED_FILE}" $(vscode-link "${LINE}" ${FILE} | tr -d "\n")
