#!/bin/bash

REGX_DATE="[><#][0-9]{4}-[0-9]{2}-[0-9]{2}"
REGX_DATES="( *${REGX_DATE} *)+"
REGX_STATE="(${REGX_DATE}) ~([0-9]+)x~"

# export DEBUG=TRUE

function debug-file() {
	test -z "${DEBUG}" || (echo "${1:?ARG1=ContextString}" && cat "${2:?ARG2=FileName}")
}

function reduce-dates() {
	SEDDATE="${1}"
	FILE="${2}"
	# Insert `|` to seperate ending dates from rest of content of task 
	# 	... on lines that don't have `|` and end with dates ... 
	# 	... regardless if they have the term or not ... or are tasks or not ...
	debug-file "Pre Single Quotes" "${FILE}"
	gsed -E -i "/^.*['＇].*$/ s/['＇]/´/g" "${FILE}"
	debug-file "Pre Verticle Bar" "${FILE}"
	gsed -E -i "/^[^|]*$/ s/\s*(${REGX_DATES})$/ | \1/" "${FILE}"
	debug-file "Pre Date Reduction Bar" "${FILE}"
	# Reduce dates anywhere ... regardless if they are done or not ... so long the state was not already reduced ... regardless if it has the term or not ...
	gsed -E -i "/[|] ${REGX_STATE} ${SEDDATE}\s*$/! s/^([^|]*)[|] (${REGX_STATE})?(${REGX_DATES})$/printf '%s' '\1| '; sed-dates-reducer '\3' '\4' '\5'/e" "${FILE}" 
	# gsed -E -i "/.*[#>]${TERM}.*${SEDDATE}\s*$/ s/(.*)(${REGX_STATE})?(${REGX_DATES})/printf '1:\1 \t 2:\2 \t 3:\3 \t 4:\4 \t 5:\5 \t 6:\6'/e" "${FILE}" 
	debug-file "Post Date Reduction Bar" "${FILE}"
}

function expand-refs() {
	TERM="${1}"
	SEDDATE="${2}"
	FILE=${3}
	debug-file "Pre Expanding Refs" "${FILE}"
	gsed -E -i "/.*([*-] [[][xX-][]]|${SEDDATE}).*/! s/ ([>#]${TERM})(.*)$/ \1\2 ${SEDDATE}/" "${FILE}"
	reduce-dates "${SEDDATE}" "${FILE}"
}

function anchor-date-to-end-of-lines-with-ref() {
	TERM="${1}"
	SEDDATE="${2}"
	FILE=${3}
	# Append date to end of line ...
	gsed -E -i "/.*([*-] [[][xX-][]]|${SEDDATE}).*/! s/ ([>#]${TERM})(.*)$/ \1\2 ${SEDDATE}/" "${FILE}"
	#               ^^^^^^^^^^^^^^^^ Ignore done or canceled tasks ...
	#                               ^^^^^^^^^^^ Ignore lines that already have the right date ...
	reduce-dates "${SEDDATE}" "${FILE}"
}

function expand_refs_in_dir() (
	DIR="${1}"
	cd "${DIR}"
	TERM=${2}
	SEDDATE=$(date -v "${3}" +'>%Y-%m-%d')
	EXPANDER=${4:-expand-refs}
	# For file that contain the <term> string ... expand lines that haven't already been expanded
	# https://askubuntu.com/questions/344407/how-to-read-complete-line-in-for-loop-with-spaces
	DEFAULT_IFS=${IFS}
	IFS=$'\n'
	for file in $(egrep -E -ril "[#>]${TERM}" .)
	do
		echo expanding file "${file}"
		${EXPANDER} "${TERM}" "${SEDDATE}" "${file}"
	done
	IFS=${DEFAULT_IFS}
)

function main() {
	case ${1} in 
		constantly)
			echo "Expanding references with [>#]{constantly,always,daily}"
			expand_refs_in_dir "${NOTEPLAN_HOME}/Notes" "constantly" "+0d" anchor-date-to-end-of-lines-with-ref
			expand_refs_in_dir "${NOTEPLAN_HOME}/Notes" "always" "+0d" anchor-date-to-end-of-lines-with-ref
			expand_refs_in_dir "${NOTEPLAN_HOME}/Notes" "daily" "+0d" anchor-date-to-end-of-lines-with-ref
		;;
		today)
			echo "Expanding references with [>#]{today,td}"
			expand_refs_in_dir "${NOTEPLAN_HOME}/Notes" "today" "+0d"
			expand_refs_in_dir "${NOTEPLAN_HOME}/Notes" "td" "+0d"
		;;
		tomorrow)
			echo "Expanding references with [>#]{tomorrow,tm,1d}"
			expand_refs_in_dir "${NOTEPLAN_HOME}/Notes" "tomorrow" "+1d"
			expand_refs_in_dir "${NOTEPLAN_HOME}/Notes" "tm" "+1d"
			expand_refs_in_dir "${NOTEPLAN_HOME}/Notes" "1d" "+1d"
		;;
		next-week)
			echo "Expanding references with [>#]{week,1w}"
			expand_refs_in_dir "${NOTEPLAN_HOME}/Notes" "week" "+7d"
			expand_refs_in_dir "${NOTEPLAN_HOME}/Notes" "1w" "+7d"
		;;
		next-month)
			echo "Expanding references with [>#]{month,1m}"
			expand_refs_in_dir "${NOTEPLAN_HOME}/Notes" "month" "+1m"
			expand_refs_in_dir "${NOTEPLAN_HOME}/Notes" "1m" "+1m"
		;;
		next-weekday)
			delta=$(date-deltas next-weekday)
			echo "Expanding references with [>#]{weekday} by ${delta} days"
			expand_refs_in_dir "${NOTEPLAN_HOME}/Notes" "weekday" "${delta}"
		;;
		this-weekend)
			delta=$(date-deltas this-weekend)
			echo "Expanding references with [>#]{weekend} by ${delta} days"
			expand_refs_in_dir "${NOTEPLAN_HOME}/Notes" "weekend" "${delta}"
		;;
		next-weekend)
			delta=$(date-deltas next-weekend)
			echo "Expanding references with [>#]{next-weekend} by ${delta} days"
			expand_refs_in_dir "${NOTEPLAN_HOME}/Notes" "next-weekend" "${delta}"
		;;
		all)
			main constantly
			main today
			main tomorrow
			main next-week
			main next-month
			main next-weekday
			main this-weekend
			main next-weekend
		;;
		default)
			main today
			main next-weekday
			main constantly
		;;
		*)
			echo no options selected ...
		;;
	esac
}

# https://stackoverflow.com/questions/2683279/how-to-detect-if-a-script-is-being-sourced
(return 0 2>/dev/null) || main ${1:-default}