source ~/git/broomar/environment/loader.sh

[[ -s $(brew --prefix)/etc/profile.d/autojump.sh ]] && . $(brew --prefix)/etc/profile.d/autojump.sh

if [ -e /Users/oeid/.nix-profile/etc/profile.d/nix.sh ]; then . /Users/oeid/.nix-profile/etc/profile.d/nix.sh; fi # added by Nix installer
