source $(dirname $(dirname $(readlink ${HOME}/.bash_profile)))/loader.sh
# source ~/Workspace/git/environment/bash-loader.sh

[[ -s $(brew --prefix)/etc/profile.d/autojump.sh ]] && . $(brew --prefix)/etc/profile.d/autojump.sh

nvm use v8.12.0

. /Users/oeid/Workspace/binaries/miniconda3/etc/profile.d/conda.sh
conda activate cogenv3
