#!/bin/bash
# PURPOSE: What release am I interested in?
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
source ${DIR}/c12e-cortex-common

# Find latest release by deafault
RELEASES_AGO=${1:-0}
# Ignore nothing by default
RELEASE_IGNORE_PATTERN=${2:-"nothing-has-this-string-in-it"}

${DIR}/cortex-release-lister | jq -cr '.[1]' \
  | egrep -v "${RELEASE_IGNORE_PATTERN}" \
  | tail -n $(expr 1 + ${RELEASES_AGO} ) | head -n 1
