#!/bin/bash
# PURPOSE: What versions of the different services were released in a specific release?
echo Specified Service: ${1:?'Example Usage: cortex-release-history "c12e/cortex-graph" "cortex5-0.5.0-" 5'} >&2

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
source ${DIR}/c12e-cortex-common

# By default, this considers the latest release ...
SERVICE=${1:-$(${DIR}/cortex-release-finder)}
# Get last 5 releases by default
LIMIT=${2:-5}
# Ignore nothing by default
RELEASE_IGNORE_PATTERN=${3:-"nothing-has-this-string-in-it"}

( ${DIR}/cortex-release-lister | jq -cr '.[1]' \
  | egrep -v "${RELEASE_IGNORE_PATTERN}" | tail -n ${LIMIT} \
  | xargs -n 1 bash -c "${DIR}/cortex-release-versions \${0} | jq -cr 'select( .[1] == \"${SERVICE}\" )'" ) 2>/dev/null
