#!/bin/sh

# https://docs.github.com/en/github/using-git/changing-author-info

export OLD_EMAIL="oeid@cognitivescale.com"
export CORRECT_EMAIL="omar_eid21@yahoo.com"
export CORRECT_NAME="Omar Eid"

FILTER_BRANCH_SQUELCH_WARNING=1 git filter-branch --env-filter '

if [ "$GIT_COMMITTER_EMAIL" = "$OLD_EMAIL" ]
then
export GIT_COMMITTER_NAME="$CORRECT_NAME"
export GIT_COMMITTER_EMAIL="$CORRECT_EMAIL"
fi
if [ "$GIT_AUTHOR_EMAIL" = "$OLD_EMAIL" ]
then
export GIT_AUTHOR_NAME="$CORRECT_NAME"
export GIT_AUTHOR_EMAIL="$CORRECT_EMAIL"
fi
' --tag-name-filter cat -- --branches --tags
