#!/bin/bash

FILE=$(mktemp)
cat | sed -e 's/&nbsp;//g' > ${FILE}
xq '.' ${FILE} \
  | jq -r  '.div.div | .[] | select(.[("@class")] == "navigation-item") | .[("@aria-label")]' \
  | gsed -E 's/(.*) level ([0-9]+)/\2\1/' \
  | sed -e 's/^1//g' -e 's/^2/	/g' -e 's/^3/		/g' -e 's/^4/			/g' -e 's/^5/				/g' -e 's/^6/					/g'
rm ${FILE}
