#!/bin/bash

function ag_vscode() {
	# Turns the grep file number pointers into links that can be opened in vscode ...
	# https://stackoverflow.com/questions/296536/how-to-urlencode-data-for-curl-command
	# https://janostlund.com/2018-07-12/url-schemes
	egrep -rin ${@} \
		--exclude-dir '.git' \
		--exclude-dir '.idea' \
		"${PWD}" \
	| gsed -E -e 's#^(.*):([0-9]+):(.*)#echo "vscode://file\1:\2" | sed -e "s: :%20:g" | tr -d "\n"; echo "\t\3"#ge'
}

ag_vscode $@
